[tool.poetry]
name = "lol-audio-unpack"
version = "0.1.0"
description = "英雄联盟游戏音频文件解包工具"
authors = ["Virace <Virace@aliyun.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
lol-voice = "^1.0.3"
requests = "^2.31.0"
loguru = "^0.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
