"""配置入口与共享 schema 导出。"""

from __future__ import annotations

from .ini import (
    CONFIG_SECTION,
    DEFAULT_CONFIG_FILENAME,
    DEFAULT_DEV_CONFIG_FILENAME,
    load_command_config,
    load_command_config_from_file,
    load_settings,
    load_settings_from_config_file,
    resolve_default_config_file_path,
    resolve_default_path,
    write_command_config,
    write_command_config_to_file,
    write_settings,
    write_settings_to_config_file,
)
from .schema import (
    BASE_CONTEXT_OPTION_ATTRS,
    COMMAND_CONFIG_FIELDS,
    CONTEXT_OPTION_ATTRS,
    DEFAULT_REMOTE_LIVE_REGION,
    DEFAULT_SHARED_SETTINGS,
    SHARED_FIELDS_BY_CLI_ATTR,
    SHARED_FIELDS_BY_INI_KEY,
    SHARED_FIELDS_BY_KEY,
    SHARED_SETTING_FIELD_BY_CLI_ATTR,
    SHARED_SETTING_FIELD_BY_INI_KEY,
    SHARED_SETTING_FIELD_BY_KEY,
    SHARED_SETTING_FIELDS,
    SUPPORTED_SETTING_KEYS,
    CommandConfigField,
    ConfigSection,
    SettingKey,
    SharedSettingField,
    build_settings,
    build_settings_from_namespace,
)

__all__ = [
    "COMMAND_CONFIG_FIELDS",
    "CONFIG_SECTION",
    "CONTEXT_OPTION_ATTRS",
    "DEFAULT_CONFIG_FILENAME",
    "DEFAULT_DEV_CONFIG_FILENAME",
    "DEFAULT_REMOTE_LIVE_REGION",
    "DEFAULT_SHARED_SETTINGS",
    "SHARED_FIELDS_BY_CLI_ATTR",
    "SHARED_FIELDS_BY_INI_KEY",
    "SHARED_FIELDS_BY_KEY",
    "SHARED_SETTING_FIELDS",
    "SUPPORTED_SETTING_KEYS",
    "CommandConfigField",
    "ConfigSection",
    "SettingKey",
    "SharedSettingField",
    "build_settings",
    "load_command_config",
    "load_settings",
    "resolve_default_path",
    "write_command_config",
    "write_settings",
    "BASE_CONTEXT_OPTION_ATTRS",
    "SHARED_SETTING_FIELD_BY_CLI_ATTR",
    "SHARED_SETTING_FIELD_BY_INI_KEY",
    "SHARED_SETTING_FIELD_BY_KEY",
    "build_settings_from_namespace",
    "load_command_config_from_file",
    "load_settings_from_config_file",
    "resolve_default_config_file_path",
    "write_command_config_to_file",
    "write_settings_to_config_file",
]
